import type { AgentSuggestion } from './generate';

const HEADER = (format: string) =>
  `# Generated by Valerius — Forge Export (${format})\n# https://valerius.ai\n\n`;

export function exportAsJSON(suggestion: AgentSuggestion): string {
  return JSON.stringify(
    {
      _valerius: 'forge-export-v1',
      domain: suggestion.domain,
      kindLabel: suggestion.kindLabel,
      systemPrompt: suggestion.systemPrompt,
      tools: suggestion.tools,
      style: suggestion.style,
      features: suggestion.features,
      constraints: suggestion.constraints,
      qualityScore: suggestion.qualityScore,
      timeToValue: suggestion.timeToValue,
      refinements: suggestion.refinements,
    },
    null,
    2,
  );
}

export function exportAsLangChain(suggestion: AgentSuggestion): string {
  void suggestion.tools; // tools used inline below
  return (
    HEADER('LangChain') +
    `"""
LangChain agent skeleton — fill in the TODOs to wire up your tools and run the agent.
Usage:
  1. pip install langchain langchain-openai
  2. Set OPENAI_API_KEY (or swap ChatOpenAI for your provider)
  3. Implement the TODO tool stubs below
  4. Run: python agent.py
"""
from langchain_openai import ChatOpenAI
from langchain_core.messages import SystemMessage, HumanMessage
from langchain.agents import AgentExecutor, create_openai_functions_agent
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain.tools import tool

# ── System prompt (forged by Valerius) ─────────────────────────────────────
SYSTEM_PROMPT = """${suggestion.systemPrompt.replace(/`/g, "'").replace(/\\/g, '\\\\')}"""

# ── Tool stubs ───────────────────────────────────────────────────────────────
${suggestion.tools.length > 0 ? suggestion.tools.map((t) => `@tool\ndef ${t.toLowerCase().replace(/[^a-z0-9]/g, '_')}(query: str) -> str:\n    """${t} — TODO: implement this tool."""\n    raise NotImplementedError("${t} not yet implemented")\n`).join('\n') : '# No tools detected — add your own here\n'}
tools = [
${suggestion.tools.length > 0 ? suggestion.tools.map((t) => `    ${t.toLowerCase().replace(/[^a-z0-9]/g, '_')},`).join('\n') : '    # TODO: add tools'}
]

# ── Agent setup ──────────────────────────────────────────────────────────────
llm = ChatOpenAI(model="gpt-4o", temperature=0.7)  # TODO: adjust model

prompt = ChatPromptTemplate.from_messages([
    ("system", SYSTEM_PROMPT),
    MessagesPlaceholder(variable_name="chat_history", optional=True),
    ("human", "{input}"),
    MessagesPlaceholder(variable_name="agent_scratchpad"),
])

agent = create_openai_functions_agent(llm, tools, prompt)
agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)

if __name__ == "__main__":
    result = agent_executor.invoke({"input": "Hello, what can you do?"})
    print(result["output"])
`
  );
}

export function exportAsCrewAI(suggestion: AgentSuggestion): string {
  const role = suggestion.kindLabel ?? suggestion.domain;
  const backstory = `You are a ${role} forged by Valerius. ${suggestion.systemPrompt.split('\n')[0]}`;
  return (
    HEADER('CrewAI') +
    `"""
CrewAI agent skeleton — fill in the TODOs and run your crew.
Usage:
  1. pip install crewai crewai-tools
  2. Implement the TODO task below
  3. Run: python agent.py
"""
from crewai import Agent, Task, Crew, Process
from crewai.tools import BaseTool  # TODO: import or implement your tools

# ── System prompt (forged by Valerius) ─────────────────────────────────────
SYSTEM_PROMPT = """${suggestion.systemPrompt.replace(/`/g, "'").replace(/\\/g, '\\\\')}"""

# ── Agent definition ─────────────────────────────────────────────────────────
${role.replace(/[^a-zA-Z0-9]/g, '_').toLowerCase()}_agent = Agent(
    role="${role}",
    goal="${suggestion.coreCapabilities?.slice(0, 2).join('; ') ?? suggestion.features.slice(0, 2).join('; ') ?? 'Assist users effectively'}",
    backstory="${backstory.replace(/"/g, "'")}",
    verbose=True,
    allow_delegation=False,
    tools=[
${suggestion.tools.map((t) => `        # TODO: ${t} tool`).join('\n') || '        # TODO: add tools'}
    ],
)

# ── Task definition ───────────────────────────────────────────────────────────
main_task = Task(
    description="TODO: define the primary task for this agent",
    expected_output="TODO: describe expected output",
    agent=${role.replace(/[^a-zA-Z0-9]/g, '_').toLowerCase()}_agent,
)

# ── Crew ──────────────────────────────────────────────────────────────────────
crew = Crew(
    agents=[${role.replace(/[^a-zA-Z0-9]/g, '_').toLowerCase()}_agent],
    tasks=[main_task],
    process=Process.sequential,
    verbose=True,
)

if __name__ == "__main__":
    result = crew.kickoff(inputs={"topic": "Hello, what can you do?"})
    print(result)
`
  );
}

export function exportAsAgno(suggestion: AgentSuggestion): string {
  const role = suggestion.kindLabel ?? suggestion.domain;
  return (
    HEADER('Agno (Phidata)') +
    `"""
Agno (Phidata) agent skeleton — fill in the TODOs.
Usage:
  1. pip install agno openai
  2. Set OPENAI_API_KEY
  3. Implement tool stubs
  4. Run: python agent.py
"""
from agno.agent import Agent
from agno.models.openai import OpenAIChat
from agno.tools import tool  # TODO: import actual tools

# ── System prompt (forged by Valerius) ─────────────────────────────────────
INSTRUCTIONS = """${suggestion.systemPrompt.replace(/`/g, "'").replace(/\\/g, '\\\\')}"""

# ── Tool stubs ────────────────────────────────────────────────────────────────
${suggestion.tools.length > 0 ? suggestion.tools.map((t) => `@tool\ndef ${t.toLowerCase().replace(/[^a-z0-9]/g, '_')}(query: str) -> str:\n    """${t} — TODO: implement."""\n    raise NotImplementedError\n`).join('\n') : '# No specific tools detected — add your own\n'}

# ── Agent ─────────────────────────────────────────────────────────────────────
agent = Agent(
    name="${role}",
    role="${role}",
    model=OpenAIChat(id="gpt-4o"),  # TODO: adjust model
    instructions=INSTRUCTIONS,
    tools=[
${suggestion.tools.length > 0 ? suggestion.tools.map((t) => `        ${t.toLowerCase().replace(/[^a-z0-9]/g, '_')},`).join('\n') : '        # TODO: add tools'}
    ],
    markdown=True,
    debug_mode=False,
)

if __name__ == "__main__":
    agent.print_response("Hello, what can you do?", stream=True)
`
  );
}
